### ISSUE TITLE
Add a Sample Engine with Schema Support to Pattern Lab

### ISSUE THREAD

**Issue by cybtachyon** [pattern-lab/patternlab-php-core#117]
**Summary:**
- Upgrade the data display engine to a full sample engine with schema support
- Upgrade existing Pattern Lab "Pattern Info" display to support an editor
- Add an interactive schema editor to PatternLab UI, matching existing standards

**Benefits:**
- Developers can quickly run through multiple iterations in the GUI when tweaking styles
- Stakeholders can preview exact text in the GUI without updating files
- Stakeholders can share that preview with a simple generated link

**To Do:**
- Validate use case with community
- Add patch porting over PatternKit's schema editor UI & functionality
- Review & Test

**Demo** of this functionality in action: http://patternkit.info/schema/keynote_quote

PatternLab already has an existing set of functionality dedicated to providing sample data via pre-configured JSON or YAML. However, it does not support easy on the fly composition and editing.
We have found that the ability to edit sample data in a GUI on the fly not only aids in pattern development, but also leads to easier demoing with stakeholders.

We propose adding support for JSON/YAML schema files that allow a GUI to provide an edit interface for populating patterns. We already have this GUI working with PatternKit and are looking at porting it over.

_This issue is a part of a series to fold functionality present in the nearly identical tool PatternKit in an effort to coalesce the development communities and deprecate PatternKit in favor of PatternLab. We plan on moving forwards with development starting August 21st._

**Related Reading:**
- https://github.com/aleksip/plugin-data-transform
- https://github.com/PatternBuilder
- http://patternlab.io/docs/data-overview.html
- https://github.com/pattern-lab/patternlab-php-core/issues/116

**Comment by bradfrost** [comment]
@cybtachyon Thanks so much for this, Derek! The demo looks great, and the JSON schema editor reminds me of some stuff @micahgodbolt was showing me a while ago. I'll leave it to @bmuenzenmeyer and @dmolsen to sort out the logistics of all this, but I love the concept.

**Comment by micahgodbolt** [comment]
@bradfrost that IS the JSON editor stuff i show'ed you a while ago :)

**Comment by bmuenzenmeyer** [comment]
This is interesting work indeed! Is the intent to incorporate this into the shared front end repositories shared across PL PHP and PL Node, or is it PHP only?

**Comment by cybtachyon** [comment]
@bradfrost Thanks! @micahgodbolt was indeed the original architect and we can't wait to get his code to a place where more developers can make use of it.

@bmuenzenmeyer The intent with the RH team would be to incorporate it in a manner that can be used across all PL implementations, with a focus on making sure that PL PHP is 100% first.

**Comment by cybtachyon** [comment]
Noting that if accepted we would also need a PR to https://github.com/pattern-lab/the-spec/ to update the spec.

**Comment by cybtachyon** [comment]
Closing in favor of https://github.com/pattern-lab/patternlab-node/issues/1005
