### ISSUE TITLE
Issue with PatternStateHelper

### ISSUE THREAD

**Issue by pserrer** [pattern-lab/patternlab-php-core#120]
It seems, the PatternStateHelper has some issues and marks other patterns as inreview/inprogress, even if they aren't. Maybe there's an missing condition around the lines 59-72, which checks, for the correct lineage, but I'm not sure about this...

Thanks for your support

**Comment by heinekin** [comment]
Yes I made a pull request some months ago about this issue, you can check it here : https://github.com/pattern-lab/patternlab-php-core/pull/103

**Comment by pserrer** [comment]
Already saw it and it seems, it works 👍
