### ISSUE TITLE
Parse Error when creating new project with developer edition

### ISSUE THREAD

**Issue by simonpioli** [pattern-lab/patternlab-php-core#123]
Composer install stops during the `postUpdateCmd` process with the following error:

> [Symfony\Component\Debug\Exception\FatalThrowableError]  
>   Parse error: syntax error, unexpected ')'   

This is the line:
https://github.com/pattern-lab/patternlab-php-core/blob/7dd6d483c69b4684173247f9673e907621311af4/src/PatternLab/InstallerUtil.php#L353

Further research finds that there's an open PR for this one already - https://github.com/pattern-lab/patternlab-php-core/pull/87

**Comment by NamelessCoder** [comment]
Fixed in https://github.com/pattern-lab/patternlab-php-core/pull/129, I assume you can close this issue.

**Comment by aleksip** [comment]
@NamelessCoder Looks like it, thanks.

**Comment by simonpioli** [comment]
Agreed, offending line is fixed in that diff. Thanks.
