### ISSUE TITLE
Move listeners.json and patternengines.json to ./config

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/patternlab-php-core#13]
These are more config-ish options. I shouldn't be so literal that they're related to packages.

**Comment by EvanLovely** [comment]
This would be great as I've had issues with having this directory git-ignored and also the config option of `overrideConfig: false`.

**Comment by dmolsen** [comment]
`./packages` in general was probably a mistake.

**Comment by dmolsen** [comment]
This has been addressed. I'll leave #14 open as the issue to track for changes to this feature as it moves towards release.
