### ISSUE TITLE
Consider dropping ./packages

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/patternlab-php-core#14]
Figure out what would be required to drop ./packages from the directory layout. There are some templates that are available in ./packages but maybe those need to go elsewhere in ./source or similar.

**Comment by dmolsen** [comment]
@aleksip @EvanLovely -

Looking for feedback. If I move `./packages/listeners.json` and `./packages/patternengines.json` to `./config` the only reason for `./packages` to exist is the pattern engine-specific templates for the view all view and a generic header/footer inserts. I think I can read them out of `./vendor` just fine. Sound ok to ditch `./packages` then? [Unified Asset Installer](https://github.com/pattern-lab/unified-asset-installer) could also go away at that point.

**Comment by EvanLovely** [comment]
@dmolsen I like that idea! I had a few issues with `./packages/listeners.json` being gitignored. Not really reproducible or to be worried about, but overall I like the idea of that folder being folded into `./vendor`.

**Comment by aleksip** [comment]
@dmolsen Sounds good!

**Comment by dmolsen** [comment]
The `feature-installupdate` branches of the [development edition](https://github.com/pattern-lab/edition-php-development/tree/feature-installupdate) and [core](https://github.com/pattern-lab/patternlab-php-core/tree/feature-installupdate) (_amongst others_) now support a new install process. Key points:

- All packages are installed before trying to run any PL core installer hooks so no more worrying about install order
- While I haven't run this against a non-`dev` release I'm hopeful this means we can be "looser" with dependency requirements thereby addressing #9 
- StarterKits are the first objects moved into `./source/` so, again, no more worrying about order
- `./packages` is no more and so is Unified Asset Installer as a dependency
- #13 has been addressed
- Using a PSR-4 compatible class lookup for listeners and patternengines (thx @bangpound)

I still need to play with this a bit more. Not a ton changed honestly but I'm sure there may be a quirk or two. Still to do:

- [ ] handle package uninstall. the original code looked close but unfinished
- [ ] address #15 
- [ ] figure out how we'll coordinate this BC breaking change across all of the repos. joy! this means a `v1.0.0` designation for at least core and editions. nothing else should have to change.

Take a peek at it and let me know what you all think.

**Comment by aleksip** [comment]
Tried out the `feature-installupdate` branch. Successful install & generate, `./packages` not there, `listeners.json` and `patternengines.json` found under `./config`.

Also tested installing with `plugin-data-transform`. Successful install & generate, plugin working as expected!

**Comment by dmolsen** [comment]
I was able to get the package uninstall stuff working so I feel pretty comfortable wrapping this up and pushing a release. This is currently a blocker for a number of other ideas that are currently floating around. We will need to coordinate on this as I'd like to reduce conflicts as much as I can.

Again, this will be released as `v1.0.0` because it breaks BC. I would like to see editions standardize on the following:

* a `.gitignore` that matches the drupal edition
* including `composer.lock` in editions
* looser package requirements. at first this will just be `~` on packages based on #9 . a future version bump after the Travis work is complete could be completely updated version numbers for packages.

I need to check included packages and try to map out how each references core and update how editions refer to them. Meaning, I could need to update `composer.json` for the various packages and then push new tags. I feel like pattern lab packages need to reference core as a dependency in case core changes an expected output and we need to tweak a package. But, like I said, I need to draw this out and think it through.

Would making this change on Wednesday, May 18 work for people?

**Comment by EvanLovely** [comment]
That day works for me! Been wanting to wrap up a lot of stuff we're pushing out by depending on 1.x instead of 0.x too.

**Comment by EvanLovely** [comment]
@dmolsen Just tossing an idea out there: what about bumping core to `v2.0.0` instead as `v1.0.0` feels like the original: pattern-lab/patternlab-php - anyway, just an idea :)

**Comment by dmolsen** [comment]
@EvanLovely my first thought was "no" but when looking at dependencies for the final mustache edition of this it would look odd to be pulling `2.0` of PL and be grabbing `1.x` dependencies. Especially `core`. We'll go with `2.0`.

**Comment by EvanLovely** [comment]
Awesome!! Agreed!

**Comment by dmolsen** [comment]
With `v2.0.0` out this has been addressed.
