### ISSUE TITLE
Add parsing of PL extra section in main project's composer.json

### ISSUE THREAD

**Issue by aleksip** [pattern-lab/patternlab-php-core#15]
It seems that a possible Pattern Lab extra section in the main project's `composer.json` is not parsed apart from `starterKitSuggestions` when running `composer create-project`.

This would be a nice feature to have for setting config options in an edition's `composer.json`.

**Comment by dmolsen** [comment]
Config options can now be set in an edition's `composer.json`. This feature is supported in the `feature-installupdate` branch of the development edition and core. A couple of notes...

- the config options from an edition's `composer.json` are applied after everything else has been installed. this way any option set by a package can be overridden on a per edition basis.
- the override is done silently
- i need to look at overriding options with arrays. this is a general issue with the `composer.json` config set-up. going to use a spin-off of sayings to test this.

**Comment by dmolsen** [comment]
Arrays should be handled. With no other other comments on the process I'm going to take this feature as done and will be implementing with the push of the `feature-installupdate` branch towards a release.
