### ISSUE TITLE
Feature Request: Add Ability To Config Name of Pattern Folder 

### ISSUE THREAD

**Issue by sghoweri** [pattern-lab/patternlab-php-core#151]
**or multiple pattern folders if we find this work could be more valuable combining it with the other work relating to support for multiple source directories (... I might just take that on now that I'm thinking about it)

In any case, there's litterally just 3 places in the code referencing "_patterns" - seems silly imho to require crazy symlinks or Gulp copy work -- just let us specify a different patternDir folder name and default to _patterns otherwise:

https://github.com/pattern-lab/patternlab-php-core/search?utf8=✓&q=_patterns&type=

@EvanLovely @aleksip thoughts?

**Comment by EvanLovely** [comment]
Agreed. I’d like to get a paths object that is similar to the node version so we can specify the folder for all of them: patterns, data, meta, etc. This is covered by #35 and is on the roadmap so I’ll close this down. 

PS SourceDir as an array is #32
