### ISSUE TITLE
Enable non-interactive composer mode

### ISSUE THREAD

**Issue by EvanLovely** [pattern-lab/patternlab-php-core#24]
It would be great if both `composer install` and `composer create-project` ran with the `--no-interaction` flag that should enable the "Do not ask any interactive question" option would work correctly. @dmolsen mentioned in the ["Add Travis" issue on Drupal Edition](https://github.com/pattern-lab/edition-php-drupal-standard/issues/12) that we could check for `$_ENV['COMPOSER_NO_INTERACTION']`. Here's where I see we would need to make changes:

- StarterKit installs asking to Merge or Replace in [`Fetch.php::mirrorDist`](https://github.com/pattern-lab/patternlab-php-core/blob/25c71af708d996d1e2b09490b380b3418918d58f/src/PatternLab/Fetch.php#L198)
- A utility that I believe is mainly used when the `public/` directory has been compiled into and not cleaned and can be ran into on a PL install that's been used and just has ran `composer update` - [`InstallerUtil.php::pathExists`](https://github.com/pattern-lab/patternlab-php-core/blob/25c71af708d996d1e2b09490b380b3418918d58f/src/PatternLab/InstallerUtil.php#L372)

In both cases I believe "Merge" to be the sensible default instead of "Replace".

### Uses

- Travis Builds & other automated testing
- Scripted theme or site builds that implement a Pattern Lab install as a piece of it. I maintain a [Yeoman Generator that spins up our Drupal Themes](https://github.com/phase2/generator-p2-theme) that could use this.
- An easy way to enable sensible defaults that should "just work"

**Comment by EvanLovely** [comment]
Quoting @dmolsen from the [other thread](https://github.com/pattern-lab/edition-php-drupal-standard/issues/12#issuecomment-219070413) :

> I think we may only be able to shut off and skip prompts in no interaction mode. I also didn't find a way to pass command line arguments through Composer. I didn't look at the actual Composer console class though so maybe there's something there.

> The prompts tend to just populate the Config tho so one could always include the defaults in the editions' config.yml to begin with. Interaction mode? User gets to override the default in config.yml. Non-interaction? Just use the default from config.yml. As for starter kits I think you already have the correct solution in travis.yml.

> I guess I'll have to add appropriate exit codes too instead of messaging if PL is in Composer's no interaction mode.

**Comment by dmolsen** [comment]
`Console::writeError()` already exits with `exit(1)` so I think the exit code issue is covered. No part of the program uses `exit()` for anything else. The only other ones are redundant.

There are definitely other places we'll have to invoke `$_ENV['COMPOSER_NO_INTERACTION']`. Because this affects the install process I'll hold off on implementing until after #14 is out the door early next week.

**Comment by dmolsen** [comment]
Welp, I was definitely wrong about that solution. Should have been using this:

```
$event->getIO()->isInteractive();
```

This feature is in `dev`.

**Comment by dmolsen** [comment]
Oh, and PL/PHP selects option 1 as the default when installing an edition with StarterKit suggestions.

**Comment by dmolsen** [comment]
Released with `v2.2.0`
