### ISSUE TITLE
Support for `sourceDir` to be Outside of PL root

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/patternlab-php-core#33]
Allow `sourceDir` or `sorceDirs` to come from outside PL root. e.g. `../../source`.

**Comment by EvanLovely** [comment]
This already works; I've done it and @aleksip has his outside as well as [seen in his shila drupal theme docs](https://github.com/aleksip/shila-drupal-theme#integrating-with-pattern-lab).

**Comment by dmolsen** [comment]
Nice :) Btw, @aleksip, the config can be changed from the command line:

```
php core/console --config --set sourceDir="../foo"
```

Not sure if that's any easier than the directions  you have. Just offering it :)

**Comment by aleksip** [comment]
@dmolsen I actually tried that, but couldn't get it to work. I have forgotten what the problem was.
