### ISSUE TITLE
`styleguideKitPath` being set as Absolute Path

### ISSUE THREAD

**Issue by EvanLovely** [pattern-lab/patternlab-php-core#38]
After I `composer create-project` in either the Twig or Drupal Editions, I get this in `config/config.yml`:

    styleguideKitPath: /Users/Evan/dev/contrib/pl/edition-php-drupal-standard/vendor/pattern-lab/styleguidekit-twig-default

Looks like we'll need a relative path; I believe this is happening at: [`InstallerUtil.php#L618`](https://github.com/pattern-lab/patternlab-php-core/blob/79bae5173fa4c02cd3b38fa5299a27d78c7037c2/src/PatternLab/InstallerUtil.php#L618)

**Comment by dmolsen** [comment]
In `v2.1.0`
