### ISSUE TITLE
`configOverrides` needs to be more granular

### ISSUE THREAD

**Issue by EvanLovely** [pattern-lab/patternlab-php-core#40]
If I override a single config value in my Edition, and a dependency also overrides several config values; then the dependency loses **all** set values, not just the values the Edition overrides. Example:

The Drupal Edition depends on the Twig Engine and when the Drupal Edition's `composer.json`'s `extra` object **does not** contain the `config` object (i.e. no `$config['extra']['patternlab']['config']` exists), then these config lines **are present** in `config.yml` after `composer create-project` as they are the configOverrides from the Twig Engine:

```yml
twigDebug: false
twigAutoescape: html
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
```

So then I decide that the Drupal Edition should set a default of having `twigDebug` set to `true` instead of `false` cause that'd be handy, I add this to my `composer.json` file:

```diff
    "extra": {
        "patternlab": {
            "starterKitSuggestions": [
                "pattern-lab/starterkit-twig-drupal-minimal",
                "pattern-lab/starterkit-twig-demo",
                "aleksip/starterkit-shila-drupal-theme",
                "forumone/starterkit-twig-drupal-gesso"
            ],
+            "config": {
+                "twigDebug": true
+            }
        }
    }
```

What then results is the below config values being the only twig related config values present in `config.yml` after `composer create-project`:

```yml
twigDebug: true
```

I would like it if did this instead:

```diff
+twigDebug: true
-twigDebug: false
twigAutoescape: html
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
```

This appears to be handled in `InstallerUtil::packagesInstall()` [right here](https://github.com/pattern-lab/patternlab-php-core/blob/964db90e24757b048b3b03cd9b7a3da4d495f1b5/src/PatternLab/InstallerUtil.php#L627). i.e. this code:

```php
// override any configs that have been set-up
if (!empty($installerInfo["configOverrides"])) {
	foreach ($installerInfo["configOverrides"] as $option => $value) {
		Config::updateConfigOption($option,$value, true); // forces the update
	}
}
```

**Comment by dmolsen** [comment]
I'm really not sure why the other options are dropped since the update is supposed to read the file from disk which should have already been updated by the pattern engine. Therefore it should do what you want. I'll fire up my own test and get to the bottom of it. Thanks for the report.

**Comment by EvanLovely** [comment]
This was done from a fresh spin up and had no config.yml at the beginning.

**Comment by dmolsen** [comment]
I believe you :) Just sort of baffled because of the order of things but I'm sure it was something silly I did.

**Comment by dmolsen** [comment]
@EvanLovely -

I tried to recreate this with the Twig development edition and was unable to do so. If you run the following do you still see the issue?

```
composer create-project pattern-lab/edition-development-twig twig-config dev-dev
```

Admittedly it's pulling `dev` of `core` but I don't think I changed anything that would have "fixed" this. My original test of this was overriding options set by the Mustache PatternEngine and that had always worked.

**Comment by EvanLovely** [comment]
Ok, everything worked as it should after trying that; thanks!
