### ISSUE TITLE
Provide a way for plugins to manipulate global data

### ISSUE THREAD

**Issue by aleksip** [pattern-lab/patternlab-php-core#43]
The `Data` class has a setter method for pattern specific data, but there does not seem to be a way to modify global data read from the `_data` directory.

**Comment by dmolsen** [comment]
I don't think `setPatternData` is much of a setter as it's just "add a blob of data to patternSpecific array within the global data store and relate it to a specific pattern." It doesn't allow deeper modification like a find and replace. At least I'm assuming that's what you're looking for. I think this is going to need a little bit of thought over what should happen. 

Should the setter iterate over whatever for matches to a given key? Is it looking at the global key/value pairs, list items, pattern data? All three? Only one? Allow an option? If the key is found do we replace that data? Or merge? Or offer the option to do either? 

The general structure of the data store:

```
-- {keys}: (key/value pairs from `./_data`)
-- listItems: (from global `listitems` file)
-- patternSpecific: 
---- {patternPartials}: 
------ {keys}: (key/value pairs from the pattern's json/yml)
------ listItems: (from pattern's listitems file)
```

And all of that depends on when you hook into the store. The pattern partials won't be there until the `DataMergeExporter` is run.

I've probably way overthought this :) What are you ultimately looking to do?

**Comment by aleksip** [comment]
Basically I just want to go iterate through the global keys, get the values, possibly do something to the value and set the new value.

So maybe something like `getKeys()`,  `getValue($key)` and `setValue($key, $value)`?

**Comment by dmolsen** [comment]
And nested keys? Use dot notation in the key to denote depth? That would be similar to how I handle nested config vars.

**Comment by aleksip** [comment]
Ah, nested keys. They could just be left as the responsibility of the plugin, but if there is support for nested keys elsewhere it would of course be good to be consistent. Can you point me to the config var code? Could have a go at a PR if everything is otherwise ok.

**Comment by dmolsen** [comment]
Well my config setter is pretty dumb... I'll need to think on dot notation for this. I think it would be really useful.

**Comment by dmolsen** [comment]
This package might help with the setting and getting of data with dot notation. No need for me to reinvent the wheel. That said, it might push our min version supported from `5.3.6` to `5.4` which is annoying. 

https://packagist.org/packages/shudrum/array-finder

**Comment by dmolsen** [comment]
When `dev` drops this afternoon you will have access to the following options:

* `Data::get()` - returns the whole store
* `Data::getOption($key)` - returns data for a given key. supports dot notation
* `Data::setOption($key, $value)` - sets the value for a given key. supports dot notation
* `Data::replaceStore($store)` - replace the entire data store. this way you can `get()`, iterate over entire store, make changes, and push it back

`Config` supports `getOption` and `setOption` with dot notation as well. This extends to the command-line feature.

**Comment by aleksip** [comment]
A late thank you, using this now in Data Transform Plugin!
