### ISSUE TITLE
Add `--quiet` CLI option to server to suppress output

### ISSUE THREAD

**Issue by EvanLovely** [pattern-lab/patternlab-php-core#44]
I would like to be able to run this command:

    php core/console --server --quiet

And have it only output this:

```
configuring pattern lab...
server started on http://localhost:8080 - use ctrl+c to exit...
```

It currently will output stuff like this after I visit a page:

```
[Tue May 24 16:57:23 2016] 127.0.0.1:53443 [200]: /styleguide/css/styleguide.min.css
[Tue May 24 16:57:23 2016] 127.0.0.1:53451 [200]: /styleguide/bower_components/hogan-3.0.2.min.js
[Tue May 24 16:57:23 2016] 127.0.0.1:53445 [200]: /styleguide/bower_components/jquery.min.js
[Tue May 24 16:57:23 2016] 127.0.0.1:53446 [200]: /styleguide/data/patternlab-data.js
```

That's the output I would like not outputted. The reason behind this is I would like to add this to the `scripts` object of an Edition's `composer.json`:

```json
"start": "php core/console --server --quiet & php core/console --watch"
```

This would allow one to run the single command below to have a server and watch commands (i.e. starting up Pattern Lab):

```
composer run-script start
```

**Comment by dmolsen** [comment]
The built-in PHP server doesn't have a native "quiet" mode but I believe I can `/dev/null` the output by tacking on `>& /dev/null` to the server start command if the `--quiet` arg is there.

**Comment by dmolsen** [comment]
`--quiet` has been added in `dev`. Dang, I like my Console class.

**Comment by EvanLovely** [comment]
🎉👍🏼 Nice! Thanks!

**Comment by EvanLovely** [comment]
Oh, one question! After you redirect that output, does it still output that the server has started and the URL to go to?

**Comment by dmolsen** [comment]
The server started message actually fires before the server is really started. I'm making an assumption but that's the easiest way to handle it. So, yes, it still shows up.

**Comment by EvanLovely** [comment]
Perfect! 👍🏼
