### ISSUE TITLE
Load data for hidden patterns

### ISSUE THREAD

**Issue by aleksip** [pattern-lab/patternlab-php-core#58]
`RawPatternHelper` and `PatternInfoRule` will not load raw pattern data or pattern-specific data for hidden patterns (name of pattern starts with an underscore). There might be use cases, especially involving plugins, where this data is needed.

Data for hidden patterns could be loaded normally or methods for loading the data could be exposed to plugins.

**Comment by dmolsen** [comment]
Good find. I'll fix both of those.

**Comment by dmolsen** [comment]
@aleksip -

This will be part of the next release tonight. Basically I'm going to snarf in and build all the things but limit action on "hidden" to export of patterns for the styleguide and navigation. This way the Data and PatternData stores are as complete as possible.

**Comment by aleksip** [comment]
Tested 2.6.3 with Data Transform Plugin and joining and including hidden patterns now works fine. Thanks!

**Comment by dmolsen** [comment]
@aleksip -

Thanks.
