### ISSUE TITLE
Use Pattern Loader for Header & Footer

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/patternlab-php-core#60]
PL/PHP renders the `./source/_meta` header and footer using a string loader. Data can be passed but partials can't be rendered. Move to rendering them with the Pattern Loader. I'd like to see this be two renders if at all possible. One render w/ header+pattern+footer and one render w/ just the pattern. This will be a minor performance hit in the long-term as it will almost always be overkill to render without the string loader.

**Comment by dmolsen** [comment]
This issue has also been opened on spec: pattern-lab/the-spec#24

**Comment by dmolsen** [comment]
Approved from a spec perspective. This will be implemented soonish. I'm still working on docs.

**Comment by dmolsen** [comment]
@bradfrost -

This will be implemented in the next release tonight. Figured out a way to do this without too much overhead. Can fence an include like so to make sure it doesn't show up on the "view all" view (same header/footer code for patterns and that).

    {{^ viewall }}
       {{> atoms-svg
    {{/ viewall }}

**Comment by bradfrost** [comment]
@dmolsen Nice!

So that code says "Include this pattern unless you're in the viewall template"?

**Comment by dmolsen** [comment]
si, señor

**Comment by bradfrost** [comment]
That's great. That will be really helpful for quite a few things I think.

**Comment by dmolsen** [comment]
This has been pushed out as part of `v2.6.3`

**Comment by zetareticoli** [comment]
Great
