### ISSUE TITLE
Problem with getPathPHP

### ISSUE THREAD

**Issue by aleksip** [pattern-lab/patternlab-php-core#68]
`getPathPHP`, introduced in 2.5.0, is causing problems with the [Travis builds](https://travis-ci.org/pattern-lab/edition-php-drupal-standard) for the Drupal edition of PL.

The builds fail with `please add the option ``phpBin`` with the path to PHP to ./config/config.yml to run this process...`. Adding a `phpBin` path to an edition's `config.yml` doesn't seem like a good solution.

The function checks for `$_SERVER["_"]`. Maybe `PHP_BINARY` would work better? Or maybe something inspired by [Symfony's solution](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/PhpExecutableFinder.php)?

**Comment by dmolsen** [comment]
I can use Symfony's solution I think. Already using Symfony Process.

**Comment by dmolsen** [comment]
This is in `dev`.

**Comment by aleksip** [comment]
Thanks! Really nice that you are using more and more Symfony components. Using a popular framework makes it easier to understand the code and to contribute to the project. And us Drupal folks like Symfony of course. :)

**Comment by aleksip** [comment]
Drupal edition Travis builds are now passing with 2.7.0. Thanks again!
